// JavaScript Document
function tollcon()
{
	var p='<div class="toll"><pre>From : <input type="text" name="from">		To : <input type="text" name="to"></pre><br>Select Your toll : <select name="tollname" class="tolis"><option value="vijayamangalam">Vijayamangalam</option><option value="kaniyanur">Kaniyanur</option><option value="sankari">Sankari</option><option value="kancheepuram">Kancheepuram</option><option value="poonamalle">Poonamalle</option><option value="mettupalayam">Mettupalayam</option><option value="salem to cbe Hw">Salem to cbe Hw</option><option value="halli">Halli</option></select><br><br>Select vehcile : <select name="vehname"><option value="car">Car</option><option value="lorry">Lorry</option><option value="bus">Bus</option></select><br><br>Veh No : <input type="text" name="vehno"><br><br><input type="submit" style="position:absolute; left:200px; top:350px; height:40px; width:200px; background-color:#62ACA6; color:#FFFFFF; font-family:Calibri; font-size:20px;" value="Submit"></div>';
	document.getElementById("si").innerHTML=p;
}
function con1()
{
	var p='<div style=" height:530px; width:500px; background-color:#E9E9E9;"><p style="font-size:20px; color:#4B926B;"><div style="border-style:solid; height:505px; width:475px; border-color:#62ACA6; position:relative; top:10px; left:10px;"><div style="margin-left:40px;"><br><br><a href="#" onClick="con1()" style="margin-top:30px; background-color:#62ACA6; padding:20px; text-decoration:none; color:#FFFFFF; margin-left:20px;">Sign In</a><a href="#" onClick="con2()" style="margin-top:30px; background-color:#62ACA6; padding:20px; text-decoration:none; color:#FFFFFF; margin-left:100px;">Sign Up</a><br><br><p style="font-size:20px; color:#62ACA6;">Username</p><input type="text" name="usr" style=" height:30px; width:200px;"><br><p style="font-size:20px; color:#62ACA6;">PassWord</p><input type="password" name="pw" style=" height:30px; width:200px;"><br><br><input style=" height:50px; width:200px; border-radius:8px; background-color:#62ACA6; color:#F3F3F3;font-size:20px; position:relative; left:100px;" type="submit" value="Sign In"></div></div></div>';
	document.getElementById("si").innerHTML=p;
}
function con2()
{
	var p='<div style=" height:930px; width:500px; background-color:#E9E9E9;"><p style="font-size:20px; color:#4B926B;"><div style="border-style:solid; height:905px; width:475px; border-color:#62ACA6; position:relative; top:10px; left:10px;"><div style="margin-left:40px;"><br><br><a href="#" onClick="con1()" style="margin-top:30px; background-color:#62ACA6; padding:20px; text-decoration:none; color:#FFFFFF; margin-left:20px;">Sign In</a><a href="#" onClick="con2()" style="margin-top:30px; background-color:#62ACA6; padding:20px; text-decoration:none; color:#FFFFFF; margin-left:100px;">Sign Up</a><br><br><p style="font-size:20px; color:#62ACA6;">FirstName</p><input type="text" name="first" style=" height:30px; width:200px;"><br><p style="font-size:20px; color:#62ACA6;">UserName</p><input type="text" name="user" style=" height:30px; width:200px;"><br><p style="font-size:20px; color:#62ACA6;">Address</p><textarea name="add" rows=6 cols=35></textarea><br><p style="font-size:20px; color:#62ACA6;">Mobile Number</p><input type="text" name="mob" style=" height:30px; width:200px;"><br><p style="font-size:20px; color:#62ACA6;">e-mail</p><input type="email" name="ema" style=" height:30px; width:200px;"><p style="font-size:20px; color:#62ACA6;">PassWord</p><input type="password" name="pass" style=" height:30px; width:200px;"><br><br><input style=" height:50px; width:200px; border-radius:8px; background-color:#62ACA6; color:#F3F3F3;font-size:20px; position:relative; left:100px;" type="submit" value="Sign up"></div></div></div>';
	document.getElementById("si").innerHTML=p;
}